# Generated by Django 3.2.5 on 2021-07-08 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id_alumn', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Alumn',
                'verbose_name_plural': 'Alumns',
                'db_table': 'alumns',
                'ordering': ['id_alumn'],
            },
        ),
        migrations.CreateModel(
            name='Alumn_Classroom',
            fields=[
                ('id_alumnClassroom', models.AutoField(primary_key=True, serialize=False)),
                ('id_alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumn')),
            ],
            options={
                'verbose_name': 'Alumn_Classroom',
                'verbose_name_plural': 'Alumn_Classrooms',
                'db_table': 'alumn_classroom',
                'ordering': ['id_alumnClassroom'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['id_course'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=255)),
                ('especiality', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'techers',
                'ordering': ['id_teacher'],
            },
        ),
        migrations.CreateModel(
            name='Course_Alumn',
            fields=[
                ('id_courseAlumn', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(default=0.0)),
                ('id_alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumn')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'Course_Alumn',
                'verbose_name_plural': 'Course_Alumns',
                'db_table': 'course_clumn',
                'ordering': ['id_courseAlumn'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id_classroom', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.CharField(max_length=255)),
                ('grado', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=15)),
                ('status', models.IntegerField(default=1)),
                ('alumns', models.ManyToManyField(through='app.Alumn_Classroom', to='app.Alumn')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'classrooms',
                'ordering': ['id_classroom'],
            },
        ),
        migrations.CreateModel(
            name='Assistance_Alumn',
            fields=[
                ('id_assistance', models.AutoField(primary_key=True, serialize=False)),
                ('assistance_alumn', models.DateTimeField()),
                ('id_alumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumn')),
            ],
            options={
                'verbose_name': 'Assistance_Alumn',
                'verbose_name_plural': 'Assistance_Alumns',
                'db_table': 'assistance_alumn',
                'ordering': ['id_assistance'],
            },
        ),
        migrations.AddField(
            model_name='alumn_classroom',
            name='id_classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom'),
        ),
    ]
